42-dynamic-profile-screen
ETLOnline/spark pull request #48
Opened 2024-12-27 13:38 UTC by BlazingC0der

2024-12-28 10:13 UTC, usama-tariq1 requested changes
No Good To Me

2024-12-28 10:13 UTC, usama-tariq1 commented on package.json
> +    "uuid": "^11.0.3"
why do you need extra package for uuid

2024-12-28 10:13 UTC, usama-tariq1 commented on src/app/(dashboard)/profile/[id]/page.tsx
>  const recommendations = [
can you remove all this mock data since we have all dynamic stuff

2024-12-28 10:13 UTC, usama-tariq1 commented on src/app/(dashboard)/profile/page.tsx
> +import ProfileActivities from "@/src/components/dashboard/Profile/profile-activities"
for future ref please use ProfileActivities.tsx 
for custom components 
its alright for shadcn component but we will be not be using slug type file names

2024-12-28 10:13 UTC, usama-tariq1 commented on src/app/api/webhook/user-created/route.ts
> +console.log("webhook user created");
remove this console please

2024-12-28 10:13 UTC, usama-tariq1 commented on src/components/HomeLayoutComponents/HeaderComponent.tsx
> +// import { CreateServerAction } from "@/src/server-actions"
remove commented or unused code

2024-12-28 10:13 UTC, usama-tariq1 commented on src/components/HomeLayoutComponents/HeaderComponent.tsx
> +import { CreateUser } from "@/src/db/data-access/user/query"
dont use query in client component 
use via Server action

2024-12-28 10:13 UTC, usama-tariq1 commented on src/components/HomeLayoutComponents/HeaderComponent.tsx
> +    console.log("user created", res)
dont need to console

2024-12-28 10:13 UTC, usama-tariq1 commented on src/components/HomeLayoutComponents/HeaderComponent.tsx
> +const addUser = async () => {
move this function 
for future ref dont use the query in client component

2024-12-28 10:13 UTC, usama-tariq1 commented on src/components/chips-input/index.tsx
> +  tags: Tag[]
dont need to use some many states 
A component should only expose value in one variable 
use  enums instead of using strings in type

2024-12-28 10:13 UTC, usama-tariq1 commented on src/components/chips-input/index.tsx
> +    useServerAction(SearchTagsForSuggestions)
A representational Component should not contain any external or business logic
Think about it this component can not be reused

2024-12-28 10:13 UTC, usama-tariq1 commented on src/components/chips-input/index.tsx
> +      <div className="flex flex-wrap gap-2 rounded-md border border-input bg-transparent p-2 focus-within:ring-1 focus-within:ring-ring">
use all the styling in style sheet for a representational component

2024-12-28 10:13 UTC, usama-tariq1 commented on src/components/dashboard/profile/edit-profile-modal.tsx
> +  setBio: (value: string | ((bio: string) => string)) => void
modal should have its own contained states 
you can receive one united global state from jotai

2024-12-28 10:13 UTC, usama-tariq1 commented on src/components/dashboard/profile/edit-profile-modal.tsx
> +  ] = useServerAction(AddExistingTagsForUser)
server action should be suffixed with Server at the end

2024-12-28 10:13 UTC, usama-tariq1 commented on src/components/dashboard/profile/edit-profile-modal.tsx
> +    useServerAction(DeleteTagsForUser)
suffix for Server

2024-12-28 10:13 UTC, usama-tariq1 commented on src/components/dashboard/profile/edit-profile-modal.tsx
> +    useServerAction(UpdateBioForUser)
suffix

2024-12-28 10:13 UTC, usama-tariq1 commented on src/components/dashboard/profile/edit-profile-modal.tsx
> +      (await updateTags(
dont use separate tag Server action only save on submit

2024-12-28 10:13 UTC, usama-tariq1 commented on src/components/dashboard/profile/edit-profile-modal.tsx
> +    updatedInterests.length &&
dont need to call action for every single input

2024-12-28 10:13 UTC, usama-tariq1 commented on src/components/dashboard/profile/edit-profile-modal.tsx
> +        <form onSubmit={saveProfileChanges} className="edit-profile-form">
please use form Data and validate on submit 
via zod on front end to show errors 
and on Server action to check validity

2024-12-28 10:13 UTC, usama-tariq1 commented on src/components/dashboard/profile/edit-profile-modal.tsx
> +                  tags={updatedSkills}
this component should be reuseable and should only expose value and onchange function is required , you can use onInputChange with value callback function and move all business logic and server action logic to hook

2024-12-28 10:13 UTC, usama-tariq1 commented on src/components/dashboard/profile/profile-activities.tsx
> +  const [activitiesLoading, activities, activitiesError, getActivities] =
this can be loaded on server side don't need to load everything on client side

2024-12-28 10:13 UTC, usama-tariq1 commented on src/components/dashboard/profile/profile-activities.tsx
> +    ;(async () => {
await is of no use in Effect
just function call is sufficent unless you want to get the data in Effect 
then use a separate  async handle function

2024-12-28 10:13 UTC, usama-tariq1 commented on src/components/dashboard/profile/profile-activities.tsx
> +            activities?.data.map((activity) => (
data can be null as well check success before hand

2024-12-28 10:13 UTC, usama-tariq1 commented on src/components/dashboard/profile/profile-bio.tsx
> +      text: "An exceptional developer with a keen eye for detail."
dont need this demo data any more if screen is dynamic

2024-12-28 10:13 UTC, usama-tariq1 commented on src/components/dashboard/profile/profile-bio.tsx
> +  const { user } = useUser()
should not use user from Clerk 
as this has completly different set of information and ids
use clerk hook for profile image , name or email stuff 
again thats all available in Jotai store -> userStore

2024-12-28 10:13 UTC, usama-tariq1 commented on src/components/dashboard/profile/profile-bio.tsx
> +  const [getBioLoading, bioData, getBioError, getBio] =
dont have to get everything through useServerAction 
user Action directly in server side

2024-12-28 10:13 UTC, usama-tariq1 commented on src/components/dashboard/profile/profile-bio.tsx
> +              bio={bio}
dont need to pass all of this is global jotai state is managed

2024-12-28 10:13 UTC, usama-tariq1 commented on src/components/dashboard/profile/profile-rewards.tsx
> +    GetRewardsForUserAction
can be fetched server side and passed and hydrate severside

2024-12-28 10:13 UTC, usama-tariq1 commented on src/components/dashboard/profile/profile-rewards.tsx
> +            rewards.data &&
data can be null 
please use ternary operate and not && 
this is why 
[https://medium.com/@davidkelley87/avoiding-in-reacts-conditional-rendering-dec9eb61ee65#:~:text=Using%20%E2%80%9C%26%26%E2%80%9D%20to%20conditionally%20render%20components%20can%20lead%20to%20unexpected,evaluate%20to%20the%20expected%20value.](url)

2024-12-28 10:13 UTC, usama-tariq1 commented on src/components/dashboard/profile/types/profile-types.d.ts
> +  status: "saved" | "selected" | "new"
use enums instead of strings

2024-12-28 10:13 UTC, usama-tariq1 commented on src/components/dashboard/profile/user/ProfileFollowActions.tsx
> +    console.log(Iam?.unique_id, user.unique_id , "get Contact")
remove console.

2024-12-28 10:13 UTC, usama-tariq1 commented on src/components/dashboard/profile/user/ProfileFollowActions.tsx
> +    console.log(Iam?.unique_id, user.unique_id , "get Contact")
this is to @usama-tariq1

2024-12-28 10:13 UTC, usama-tariq1 commented on src/db/data-access/user-reward/query.ts
> +export const AddRewardForUser = async (data: InsertUserReward[]) => {
for future ref 
create this query in rewards/query.ts 
as this can be difficult to manage after so many relations

2024-12-28 10:13 UTC, usama-tariq1 commented on src/db/data-access/user-tag/query.ts
> +export const AddUserTag = async (data: InsertUserTag[]) => {
move to tags/query.ts

2024-12-28 10:13 UTC, usama-tariq1 commented on src/db/data-access/user/query.ts
> +export const GetUserBio = async (userId: string) => {
dont understand this query

2024-12-28 10:13 UTC, usama-tariq1 commented on src/db/data-access/user/query.ts
> +export async function UpdateUserBio(userId: string, bio: string) {
use relations for query

2024-12-28 10:13 UTC, usama-tariq1 commented on src/db/migrations/0008_clean_apocalypse.sql
> +ALTER TABLE `users` ADD `bio` text;--> statement-breakpoint
dont need to add skills interests here
make sparate table 
if you already made that please delete this migration 
or this could cause some unwanted issue on fresh migration

2024-12-28 10:13 UTC, usama-tariq1 commented on src/db/migrations/0008_clean_apocalypse.sql
> +ALTER TABLE `users` ADD `bio` text;--> statement-breakpoint
leave it as is for now

2024-12-28 10:13 UTC, usama-tariq1 commented on src/db/migrations/0009_silent_hammerhead.sql
> +CREATE TABLE `interests` (
drop these as well i think

2024-12-28 10:13 UTC, usama-tariq1 commented on src/db/schema.ts
> +  unique_id: text("unique_id", { length: 36 }).$defaultFn(() => uuidv4()),
your plugin is making mess in other files

2024-12-28 10:13 UTC, usama-tariq1 commented on src/db/schema.ts
> +  userChats: many(userChatsTable)
why would you remove userContacts relations

2024-12-28 10:13 UTC, usama-tariq1 commented on src/db/schema.ts
> +  userChats: many(userChatsTable)
and types

2024-12-28 10:13 UTC, usama-tariq1 commented on src/db/schema.ts
> +})
these are unwanted conflicts that i dont want to resolve 
please mute your plugin

2024-12-28 10:13 UTC, usama-tariq1 commented on src/db/schema.ts
> +}))
why would you remove stuff ?

2024-12-28 10:13 UTC, usama-tariq1 commented on src/db/schema.ts
> +}))
types are deleted here as well

2024-12-28 10:13 UTC, usama-tariq1 commented on src/db/schema.ts
> +export type InsertUser = typeof usersTable.$inferInsert
dont make all the types in acculating all in one place 
very difficult to see the whole image

2024-12-28 10:13 UTC, usama-tariq1 commented on src/server-actions/Tag/Tag.ts
> +export const AddNewTagsForUser = CreateServerAction(
suffix "Action"

2024-12-28 10:13 UTC, usama-tariq1 commented on src/server-actions/Tag/Tag.ts
> +  false,
use true here as all of this should be authenticated

2024-12-28 10:13 UTC, usama-tariq1 commented on src/server-actions/Reward/Reward.ts
> +  false,
true

2024-12-28 10:13 UTC, usama-tariq1 commented on src/server-actions/Reward/Reward.ts
> +  false,
should be true everything on profile should be authenticated 
expect some of the get ones

2024-12-28 10:13 UTC, usama-tariq1 commented on src/server-actions/Tag/Tag.ts
> +  false,
true

2024-12-28 10:13 UTC, usama-tariq1 commented on src/server-actions/Tag/Tag.ts
> +export const AddExistingTagsForUser = CreateServerAction(
Action suffix

2024-12-28 10:13 UTC, usama-tariq1 commented on src/server-actions/Tag/Tag.ts
> +  false,
true

2024-12-28 10:13 UTC, usama-tariq1 commented on src/server-actions/Tag/Tag.ts
> +  false,
true

2024-12-28 10:13 UTC, usama-tariq1 commented on src/server-actions/Tag/Tag.ts
> +export const GetTagsForUser = CreateServerAction(
Sever Suffix

2024-12-28 10:13 UTC, usama-tariq1 commented on src/server-actions/Tag/Tag.ts
> +export const SearchTagsForSuggestions = CreateServerAction(
Server suffix

2024-12-28 10:13 UTC, usama-tariq1 commented on src/server-actions/User/User.ts
> +export const UpdateBioForUser = CreateServerAction(
suffix Server

2024-12-28 10:13 UTC, usama-tariq1 commented on src/server-actions/User/User.ts
> +  false,
true

2024-12-28 10:13 UTC, usama-tariq1 commented on src/server-actions/User/User.ts
> +export const GetUserBioForUser = CreateServerAction(
suffix

2024-12-28 10:13 UTC, usama-tariq1 commented on src/server-actions/index.ts
> +    //     throw new Error("Unauthorized", { cause: 401 });
why why why why ????

2024-12-28 10:14 UTC, usama-tariq1 commented
plus the conflicts 👎

2024-12-30 05:48 UTC, BlazingC0der commented on package.json
> +    "uuid": "^11.0.3"
the default Node crypto package was causing an issue while migrating changes, this package was supposed to be a makeshift fix but i forgot to remove it later.

2024-12-30 05:52 UTC, BlazingC0der commented on src/app/(dashboard)/profile/[id]/page.tsx
>  const recommendations = [
sure thing

2024-12-30 06:00 UTC, BlazingC0der commented on src/app/(dashboard)/profile/page.tsx
> +import ProfileActivities from "@/src/components/dashboard/Profile/profile-activities"
ok sure but there's a mix of kebab-case and PascalCase file names in the components folder, shouldn't we follow a single convention as such a mix is kinda confusing, and I'm not talking about shadcn components here.

2024-12-30 06:04 UTC, BlazingC0der commented on src/components/HomeLayoutComponents/HeaderComponent.tsx
> +import { CreateUser } from "@/src/db/data-access/user/query"
this is dead code which i forgot to remove, my bad!

2024-12-30 06:45 UTC, BlazingC0der commented on src/components/dashboard/profile/edit-profile-modal.tsx
> +  ] = useServerAction(AddExistingTagsForUser)
Action or Server?

2024-12-30 06:52 UTC, BlazingC0der commented on src/components/dashboard/profile/edit-profile-modal.tsx
> +      (await updateTags(
updateTags isn't a server action, rather it's a helper function declared inside the file itself

2024-12-30 06:54 UTC, BlazingC0der commented on src/components/dashboard/profile/edit-profile-modal.tsx
> +        <form onSubmit={saveProfileChanges} className="edit-profile-form">
exactly what kinda validation do we need here? I mean bio and skills/interests can contain pretty much everything, any alphanumeric character combination right?

2024-12-30 07:02 UTC, BlazingC0der commented on src/components/dashboard/profile/profile-activities.tsx
> +  const [activitiesLoading, activities, activitiesError, getActivities] =
shouldn't server components be stateless? secondly the profile page had to be made a client component due to those tabs so its children cant be rendered on server.

2024-12-30 07:03 UTC, BlazingC0der commented on src/components/dashboard/profile/profile-activities.tsx
> +            activities?.data.map((activity) => (
doesn't activities.data && suffice for null checks?

2024-12-30 07:07 UTC, BlazingC0der commented on src/components/dashboard/profile/profile-bio.tsx
> +      text: "An exceptional developer with a keen eye for detail."
we didn't discuss anything about recommendations when creating the issue, should I create a table for recommendations as well?

2024-12-30 07:11 UTC, BlazingC0der commented on src/components/dashboard/profile/profile-bio.tsx
> +  const [getBioLoading, bioData, getBioError, getBio] =
ProfileBio is rendered client side as it's the child of a client component

2024-12-30 09:16 UTC, BlazingC0der commented on src/db/data-access/user/query.ts
> +export async function UpdateUserBio(userId: string, bio: string) {
?? plz elaborate

2025-01-12 11:33 UTC, closed without merging