post feed integration
ETLOnline/spark pull request #7
Opened 2024-12-05 13:46 UTC by BlazingC0der

breaking down post feed from v0 into smaller components + integration into a makeshift posts page

2024-12-05 14:01 UTC, usama-tariq1 requested changes
Please review some requested changes

2024-12-05 14:01 UTC, usama-tariq1 commented on src/components/dashboard/posts/post-comments.tsx
> +import { Comment } from "@/src/app/(dashboard)/posts/page"
if Comment is the type create a file or folder  inside that component folder to add types / interfaces / contants

2024-12-05 14:01 UTC, usama-tariq1 commented on src/components/dashboard/posts/post-feed.tsx
> +const PostFeed: React.FC<Props> = (props) => {
it would be cleaner if you can create components for each feed/post type

2024-12-05 14:01 UTC, usama-tariq1 commented on src/app/(dashboard)/posts/page.tsx
> +    content: "/images/coding-setup.jpg",
this image does not exist in code base can you add sample image and use skeleton for loading that image , plus

2024-12-05 14:12 UTC, BlazingC0der commented on src/components/dashboard/posts/post-feed.tsx
> +const PostFeed: React.FC<Props> = (props) => {
how about a single component with variants for each post type

2024-12-06 15:16 UTC, usama-tariq1 approved these changes

2024-12-06 15:16 UTC, usama-tariq1 commented on src/components/dashboard/posts/post-content.tsx
> +    <>
improvement for future -> use separate component for each post type rather then same file each post type should have its counter part / components in that post type 
e.g <ImagePost /> <TextPost /> <FilePost /> 
so in the future if you want to show different kind of options /actions to a post type can be easily done with out refactoring

2024-12-06 15:25 UTC, merged